server:
  port: 8085

spring:
  application:
    name: Config-Server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ashish4578/FirstMicoservices
          clone-on-start: true
          search-paths: ConfigProfiles