server:
  port: 8081
spring:
  application:
   name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_user
    username: root
    password: Sql#1541
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:  configserver:http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances: 
      hotelRatingBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState : 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances: 
      hotelRatingRetry:
        max-attempts: 3
        wait-duration: 5 